import Foundation

/// Lightweight emoji shortcode dataset + search, used by the `:name:` composer
/// autocomplete. Names follow the common Discord/GitHub shortcode convention.
enum EmojiData {
    struct Emoji: Identifiable, Hashable {
        let name: String
        let char: String
        let keywords: [String]
        var id: String { name }
    }

    /// Exact shortcode → emoji. Used for the "type `:joy:` fully" auto-replace path.
    static func exact(_ name: String) -> String? {
        let n = name.lowercased()
        return byName[n]
    }

    /// Ranked search: exact name, then literal prefix, then literal substring,
    /// then keyword hits, then fuzzy subsequence matches underneath. Ordering is
    /// fully deterministic (length, then alphabetical) so the popup never flickers
    /// or reorders between keystrokes.
    static func search(_ query: String, limit: Int = 30) -> [Emoji] {
        let q = query.lowercased()
        guard !q.isEmpty else { return [] }

        var exact: [Emoji] = []
        var prefix: [Emoji] = []
        var contains: [Emoji] = []
        var keyword: [Emoji] = []
        var fuzzy: [(Emoji, Double)] = []

        for e in all {
            if e.name == q {
                exact.append(e)
            } else if e.name.hasPrefix(q) {
                prefix.append(e)
            } else if e.name.contains(q) {
                contains.append(e)
            } else if e.keywords.contains(where: { $0 == q || $0.hasPrefix(q) }) {
                keyword.append(e)
            } else {
                let s = fuzzyScore(query: q, in: e.name)
                if s >= 0.8 { fuzzy.append((e, s)) }
            }
        }

        func byLengthThenName(_ a: Emoji, _ b: Emoji) -> Bool {
            if a.name.count != b.name.count { return a.name.count < b.name.count }
            return a.name < b.name
        }
        prefix.sort(by: byLengthThenName)
        contains.sort(by: byLengthThenName)
        keyword.sort(by: byLengthThenName)
        fuzzy.sort { $0.1 != $1.1 ? $0.1 > $1.1 : $0.0.name < $1.0.name }

        var out: [Emoji] = []
        var seen = Set<String>()
        for e in exact + prefix + contains + keyword + fuzzy.map(\.0) {
            if seen.insert(e.name).inserted { out.append(e) }
            if out.count >= limit { break }
        }
        return out
    }

    private static func fuzzyScore(query: String, in text: String) -> Double {
        guard !query.isEmpty else { return 0 }
        var qi = query.startIndex
        var matched = 0
        for ch in text {
            if qi < query.endIndex && ch == query[qi] {
                matched += 1
                qi = query.index(after: qi)
            }
        }
        return Double(matched) / Double(query.count)
    }

    private static let byName: [String: String] = {
        Dictionary(uniqueKeysWithValues: all.map { ($0.name, $0.char) })
    }()

    static let all: [Emoji] = [
        // Smileys & emotion
        .init(name: "grinning", char: "😀", keywords: ["smile", "happy"]),
        .init(name: "smiley", char: "😃", keywords: ["happy", "joy"]),
        .init(name: "smile", char: "😄", keywords: ["happy", "joy", "laugh"]),
        .init(name: "grin", char: "😁", keywords: ["happy"]),
        .init(name: "laughing", char: "😆", keywords: ["lol", "haha"]),
        .init(name: "sweat_smile", char: "😅", keywords: ["relief"]),
        .init(name: "rofl", char: "🤣", keywords: ["lol", "rolling", "laugh"]),
        .init(name: "joy", char: "😂", keywords: ["lol", "tears", "laugh", "cry"]),
        .init(name: "slightly_smiling_face", char: "🙂", keywords: ["smile"]),
        .init(name: "upside_down_face", char: "🙃", keywords: ["silly"]),
        .init(name: "wink", char: "😉", keywords: ["flirt"]),
        .init(name: "blush", char: "😊", keywords: ["smile", "shy"]),
        .init(name: "innocent", char: "😇", keywords: ["angel", "halo"]),
        .init(name: "smiling_face_with_three_hearts", char: "🥰", keywords: ["love", "adore"]),
        .init(name: "heart_eyes", char: "😍", keywords: ["love", "crush"]),
        .init(name: "star_struck", char: "🤩", keywords: ["amazed", "stars"]),
        .init(name: "kissing_heart", char: "😘", keywords: ["kiss", "love"]),
        .init(name: "kissing", char: "😗", keywords: ["kiss"]),
        .init(name: "kissing_closed_eyes", char: "😚", keywords: ["kiss"]),
        .init(name: "kissing_smiling_eyes", char: "😙", keywords: ["kiss"]),
        .init(name: "yum", char: "😋", keywords: ["tasty", "delicious"]),
        .init(name: "stuck_out_tongue", char: "😛", keywords: ["tongue"]),
        .init(name: "stuck_out_tongue_winking_eye", char: "😜", keywords: ["tongue", "wink"]),
        .init(name: "zany_face", char: "🤪", keywords: ["crazy", "goofy"]),
        .init(name: "stuck_out_tongue_closed_eyes", char: "😝", keywords: ["tongue"]),
        .init(name: "money_mouth_face", char: "🤑", keywords: ["money", "rich"]),
        .init(name: "hugs", char: "🤗", keywords: ["hug"]),
        .init(name: "hand_over_mouth", char: "🤭", keywords: ["oops", "giggle"]),
        .init(name: "shushing_face", char: "🤫", keywords: ["quiet", "shh"]),
        .init(name: "thinking", char: "🤔", keywords: ["think", "hmm"]),
        .init(name: "zipper_mouth_face", char: "🤐", keywords: ["silence"]),
        .init(name: "raised_eyebrow", char: "🤨", keywords: ["skeptic", "suspicious"]),
        .init(name: "neutral_face", char: "😐", keywords: ["meh"]),
        .init(name: "expressionless", char: "😑", keywords: ["blank"]),
        .init(name: "no_mouth", char: "😶", keywords: ["silent"]),
        .init(name: "smirk", char: "😏", keywords: ["smug"]),
        .init(name: "unamused", char: "😒", keywords: ["meh", "annoyed"]),
        .init(name: "roll_eyes", char: "🙄", keywords: ["eyeroll"]),
        .init(name: "grimacing", char: "😬", keywords: ["awkward", "yikes"]),
        .init(name: "lying_face", char: "🤥", keywords: ["liar", "pinocchio"]),
        .init(name: "relieved", char: "😌", keywords: ["calm"]),
        .init(name: "pensive", char: "😔", keywords: ["sad"]),
        .init(name: "sleepy", char: "😪", keywords: ["tired"]),
        .init(name: "drooling_face", char: "🤤", keywords: ["drool"]),
        .init(name: "sleeping", char: "😴", keywords: ["zzz", "tired"]),
        .init(name: "mask", char: "😷", keywords: ["sick", "ill"]),
        .init(name: "face_with_thermometer", char: "🤒", keywords: ["sick", "fever"]),
        .init(name: "face_with_head_bandage", char: "🤕", keywords: ["hurt", "injury"]),
        .init(name: "nauseated_face", char: "🤢", keywords: ["sick", "gross"]),
        .init(name: "vomiting_face", char: "🤮", keywords: ["sick", "puke"]),
        .init(name: "sneezing_face", char: "🤧", keywords: ["sick"]),
        .init(name: "hot_face", char: "🥵", keywords: ["heat", "sweat"]),
        .init(name: "cold_face", char: "🥶", keywords: ["freezing"]),
        .init(name: "woozy_face", char: "🥴", keywords: ["drunk", "dizzy"]),
        .init(name: "dizzy_face", char: "😵", keywords: ["dead", "knocked out"]),
        .init(name: "exploding_head", char: "🤯", keywords: ["mind blown"]),
        .init(name: "cowboy_hat_face", char: "🤠", keywords: ["cowboy"]),
        .init(name: "partying_face", char: "🥳", keywords: ["party", "celebrate"]),
        .init(name: "sunglasses", char: "😎", keywords: ["cool"]),
        .init(name: "nerd_face", char: "🤓", keywords: ["geek", "smart"]),
        .init(name: "monocle_face", char: "🧐", keywords: ["inspect"]),
        .init(name: "confused", char: "😕", keywords: ["puzzled"]),
        .init(name: "worried", char: "😟", keywords: ["concern"]),
        .init(name: "slightly_frowning_face", char: "🙁", keywords: ["sad"]),
        .init(name: "frowning_face", char: "☹️", keywords: ["sad"]),
        .init(name: "open_mouth", char: "😮", keywords: ["wow", "surprised"]),
        .init(name: "hushed", char: "😯", keywords: ["surprised"]),
        .init(name: "astonished", char: "😲", keywords: ["shocked"]),
        .init(name: "flushed", char: "😳", keywords: ["embarrassed", "blush"]),
        .init(name: "pleading_face", char: "🥺", keywords: ["puppy", "beg"]),
        .init(name: "frowning", char: "😦", keywords: ["sad"]),
        .init(name: "anguished", char: "😧", keywords: ["pain"]),
        .init(name: "fearful", char: "😨", keywords: ["scared"]),
        .init(name: "cold_sweat", char: "😰", keywords: ["nervous"]),
        .init(name: "disappointed_relieved", char: "😥", keywords: ["phew"]),
        .init(name: "cry", char: "😢", keywords: ["sad", "tear"]),
        .init(name: "sob", char: "😭", keywords: ["cry", "bawl", "sad"]),
        .init(name: "scream", char: "😱", keywords: ["fear", "shock"]),
        .init(name: "confounded", char: "😖", keywords: ["frustrated"]),
        .init(name: "persevere", char: "😣", keywords: ["struggle"]),
        .init(name: "disappointed", char: "😞", keywords: ["sad"]),
        .init(name: "sweat", char: "😓", keywords: ["nervous"]),
        .init(name: "weary", char: "😩", keywords: ["tired"]),
        .init(name: "tired_face", char: "😫", keywords: ["exhausted"]),
        .init(name: "yawning_face", char: "🥱", keywords: ["bored", "tired"]),
        .init(name: "triumph", char: "😤", keywords: ["proud", "huff"]),
        .init(name: "rage", char: "😡", keywords: ["angry", "mad"]),
        .init(name: "angry", char: "😠", keywords: ["mad"]),
        .init(name: "cursing_face", char: "🤬", keywords: ["swear", "mad"]),
        .init(name: "smiling_imp", char: "😈", keywords: ["devil", "evil"]),
        .init(name: "imp", char: "👿", keywords: ["devil", "evil"]),
        .init(name: "skull", char: "💀", keywords: ["dead", "death"]),
        .init(name: "skull_and_crossbones", char: "☠️", keywords: ["danger", "poison"]),
        .init(name: "poop", char: "💩", keywords: ["shit", "crap"]),
        .init(name: "clown_face", char: "🤡", keywords: ["clown"]),
        .init(name: "ghost", char: "👻", keywords: ["spooky", "halloween"]),
        .init(name: "alien", char: "👽", keywords: ["ufo", "space"]),
        .init(name: "robot", char: "🤖", keywords: ["bot", "ai"]),
        .init(name: "jack_o_lantern", char: "🎃", keywords: ["halloween", "pumpkin"]),
        .init(name: "smiley_cat", char: "😺", keywords: ["cat"]),
        .init(name: "heart_eyes_cat", char: "😻", keywords: ["cat", "love"]),
        .init(name: "pouting_cat", char: "😾", keywords: ["cat", "angry"]),
        // Gestures & people
        .init(name: "wave", char: "👋", keywords: ["hello", "hi", "bye"]),
        .init(name: "raised_back_of_hand", char: "🤚", keywords: ["hand"]),
        .init(name: "raised_hand", char: "✋", keywords: ["stop", "hand"]),
        .init(name: "vulcan_salute", char: "🖖", keywords: ["spock"]),
        .init(name: "ok_hand", char: "👌", keywords: ["ok", "perfect"]),
        .init(name: "pinched_fingers", char: "🤌", keywords: ["italian"]),
        .init(name: "v", char: "✌️", keywords: ["peace", "victory"]),
        .init(name: "crossed_fingers", char: "🤞", keywords: ["luck", "hope"]),
        .init(name: "love_you_gesture", char: "🤟", keywords: ["love"]),
        .init(name: "metal", char: "🤘", keywords: ["rock"]),
        .init(name: "call_me_hand", char: "🤙", keywords: ["shaka"]),
        .init(name: "point_left", char: "👈", keywords: ["left"]),
        .init(name: "point_right", char: "👉", keywords: ["right"]),
        .init(name: "point_up_2", char: "👆", keywords: ["up"]),
        .init(name: "middle_finger", char: "🖕", keywords: ["fu", "rude"]),
        .init(name: "point_down", char: "👇", keywords: ["down"]),
        .init(name: "point_up", char: "☝️", keywords: ["up"]),
        .init(name: "thumbsup", char: "👍", keywords: ["+1", "yes", "like", "ok"]),
        .init(name: "thumbsdown", char: "👎", keywords: ["-1", "no", "dislike"]),
        .init(name: "fist", char: "✊", keywords: ["power", "solidarity"]),
        .init(name: "facepunch", char: "👊", keywords: ["punch", "fist bump"]),
        .init(name: "fist_left", char: "🤛", keywords: ["bump"]),
        .init(name: "fist_right", char: "🤜", keywords: ["bump"]),
        .init(name: "clap", char: "👏", keywords: ["applause", "bravo"]),
        .init(name: "raised_hands", char: "🙌", keywords: ["praise", "celebrate"]),
        .init(name: "open_hands", char: "👐", keywords: ["hug"]),
        .init(name: "palms_up_together", char: "🤲", keywords: ["pray", "cup"]),
        .init(name: "handshake", char: "🤝", keywords: ["deal", "agree"]),
        .init(name: "pray", char: "🙏", keywords: ["please", "thanks", "namaste", "high five"]),
        .init(name: "writing_hand", char: "✍️", keywords: ["write"]),
        .init(name: "nail_care", char: "💅", keywords: ["nails", "sassy"]),
        .init(name: "muscle", char: "💪", keywords: ["strong", "flex", "gym"]),
        .init(name: "leg", char: "🦵", keywords: ["kick"]),
        .init(name: "ear", char: "👂", keywords: ["listen"]),
        .init(name: "nose", char: "👃", keywords: ["smell"]),
        .init(name: "brain", char: "🧠", keywords: ["smart", "think"]),
        .init(name: "eyes", char: "👀", keywords: ["look", "see", "watch"]),
        .init(name: "eye", char: "👁️", keywords: ["look"]),
        .init(name: "tongue", char: "👅", keywords: ["taste"]),
        .init(name: "lips", char: "👄", keywords: ["kiss", "mouth"]),
        .init(name: "baby", char: "👶", keywords: ["infant"]),
        .init(name: "boy", char: "👦", keywords: ["kid"]),
        .init(name: "girl", char: "👧", keywords: ["kid"]),
        .init(name: "man", char: "👨", keywords: ["male"]),
        .init(name: "woman", char: "👩", keywords: ["female"]),
        .init(name: "person_facepalming", char: "🤦", keywords: ["facepalm", "smh"]),
        .init(name: "person_shrugging", char: "🤷", keywords: ["shrug", "idk", "dunno"]),
        .init(name: "cop", char: "👮", keywords: ["police"]),
        .init(name: "guard", char: "💂", keywords: ["soldier"]),
        .init(name: "construction_worker", char: "👷", keywords: ["build"]),
        .init(name: "prince", char: "🤴", keywords: ["royal"]),
        .init(name: "princess", char: "👸", keywords: ["royal"]),
        .init(name: "superhero", char: "🦸", keywords: ["hero"]),
        .init(name: "supervillain", char: "🦹", keywords: ["villain"]),
        .init(name: "santa", char: "🎅", keywords: ["christmas", "xmas"]),
        .init(name: "mrs_claus", char: "🤶", keywords: ["christmas"]),
        .init(name: "mage", char: "🧙", keywords: ["wizard", "magic"]),
        .init(name: "fairy", char: "🧚", keywords: ["magic"]),
        .init(name: "vampire", char: "🧛", keywords: ["dracula"]),
        .init(name: "zombie", char: "🧟", keywords: ["undead"]),
        .init(name: "person_walking", char: "🚶", keywords: ["walk"]),
        .init(name: "person_running", char: "🏃", keywords: ["run"]),
        .init(name: "dancer", char: "💃", keywords: ["dance"]),
        .init(name: "man_dancing", char: "🕺", keywords: ["dance"]),
        .init(name: "couple_with_heart", char: "💑", keywords: ["love"]),
        .init(name: "two_men_holding_hands", char: "👬", keywords: ["friends"]),
        // Hearts & symbols
        .init(name: "heart", char: "❤️", keywords: ["love", "red"]),
        .init(name: "orange_heart", char: "🧡", keywords: ["love"]),
        .init(name: "yellow_heart", char: "💛", keywords: ["love"]),
        .init(name: "green_heart", char: "💚", keywords: ["love"]),
        .init(name: "blue_heart", char: "💙", keywords: ["love"]),
        .init(name: "purple_heart", char: "💜", keywords: ["love"]),
        .init(name: "black_heart", char: "🖤", keywords: ["love"]),
        .init(name: "white_heart", char: "🤍", keywords: ["love"]),
        .init(name: "brown_heart", char: "🤎", keywords: ["love"]),
        .init(name: "broken_heart", char: "💔", keywords: ["sad", "heartbreak"]),
        .init(name: "two_hearts", char: "💕", keywords: ["love"]),
        .init(name: "sparkling_heart", char: "💖", keywords: ["love"]),
        .init(name: "heartpulse", char: "💗", keywords: ["love"]),
        .init(name: "cupid", char: "💘", keywords: ["love", "arrow"]),
        .init(name: "gift_heart", char: "💝", keywords: ["love"]),
        .init(name: "revolving_hearts", char: "💞", keywords: ["love"]),
        .init(name: "heartbeat", char: "💓", keywords: ["love"]),
        .init(name: "100", char: "💯", keywords: ["hundred", "perfect", "score"]),
        .init(name: "anger", char: "💢", keywords: ["mad"]),
        .init(name: "boom", char: "💥", keywords: ["explode", "collision"]),
        .init(name: "dizzy", char: "💫", keywords: ["star"]),
        .init(name: "sweat_drops", char: "💦", keywords: ["water"]),
        .init(name: "dash", char: "💨", keywords: ["wind", "fast"]),
        .init(name: "bomb", char: "💣", keywords: ["explode"]),
        .init(name: "speech_balloon", char: "💬", keywords: ["chat", "talk"]),
        .init(name: "thought_balloon", char: "💭", keywords: ["think"]),
        .init(name: "zzz", char: "💤", keywords: ["sleep", "tired"]),
        .init(name: "star", char: "⭐", keywords: ["favorite"]),
        .init(name: "star2", char: "🌟", keywords: ["glow"]),
        .init(name: "sparkles", char: "✨", keywords: ["shiny", "magic", "clean"]),
        .init(name: "zap", char: "⚡", keywords: ["lightning", "fast", "electric"]),
        .init(name: "fire", char: "🔥", keywords: ["lit", "hot", "flame"]),
        .init(name: "snowflake", char: "❄️", keywords: ["cold", "winter"]),
        .init(name: "rainbow", char: "🌈", keywords: ["pride", "colors"]),
        .init(name: "sunny", char: "☀️", keywords: ["sun", "weather"]),
        .init(name: "cloud", char: "☁️", keywords: ["weather"]),
        .init(name: "droplet", char: "💧", keywords: ["water"]),
        .init(name: "ocean", char: "🌊", keywords: ["wave", "water"]),
        .init(name: "check_mark", char: "✔️", keywords: ["done", "yes"]),
        .init(name: "white_check_mark", char: "✅", keywords: ["done", "yes", "ok"]),
        .init(name: "x", char: "❌", keywords: ["no", "wrong", "cross"]),
        .init(name: "heavy_multiplication_x", char: "✖️", keywords: ["times"]),
        .init(name: "negative_squared_cross_mark", char: "❎", keywords: ["no"]),
        .init(name: "warning", char: "⚠️", keywords: ["caution", "danger"]),
        .init(name: "no_entry", char: "⛔", keywords: ["stop", "forbidden"]),
        .init(name: "question", char: "❓", keywords: ["help", "ask"]),
        .init(name: "grey_question", char: "❔", keywords: ["help"]),
        .init(name: "exclamation", char: "❗", keywords: ["alert"]),
        .init(name: "bangbang", char: "‼️", keywords: ["alert"]),
        .init(name: "heavy_check_mark", char: "✔️", keywords: ["done"]),
        .init(name: "heavy_plus_sign", char: "➕", keywords: ["add"]),
        .init(name: "heavy_minus_sign", char: "➖", keywords: ["subtract"]),
        .init(name: "heavy_division_sign", char: "➗", keywords: ["divide"]),
        .init(name: "infinity", char: "♾️", keywords: ["forever"]),
        .init(name: "recycle", char: "♻️", keywords: ["green", "reuse"]),
        .init(name: "trophy", char: "🏆", keywords: ["win", "award", "champion"]),
        .init(name: "medal", char: "🏅", keywords: ["award", "winner"]),
        .init(name: "1st_place_medal", char: "🥇", keywords: ["gold", "first", "win"]),
        .init(name: "2nd_place_medal", char: "🥈", keywords: ["silver", "second"]),
        .init(name: "3rd_place_medal", char: "🥉", keywords: ["bronze", "third"]),
        .init(name: "checkered_flag", char: "🏁", keywords: ["race", "finish"]),
        .init(name: "rocket", char: "🚀", keywords: ["launch", "space", "fast", "ship"]),
        .init(name: "tada", char: "🎉", keywords: ["party", "celebrate", "congrats"]),
        .init(name: "confetti_ball", char: "🎊", keywords: ["party", "celebrate"]),
        .init(name: "balloon", char: "🎈", keywords: ["party"]),
        .init(name: "gift", char: "🎁", keywords: ["present", "birthday"]),
        .init(name: "birthday", char: "🎂", keywords: ["cake", "party"]),
        .init(name: "crown", char: "👑", keywords: ["king", "queen", "royal"]),
        .init(name: "gem", char: "💎", keywords: ["diamond", "jewel"]),
        .init(name: "moneybag", char: "💰", keywords: ["money", "rich"]),
        .init(name: "dollar", char: "💵", keywords: ["money", "cash"]),
        .init(name: "credit_card", char: "💳", keywords: ["money", "pay"]),
        .init(name: "bulb", char: "💡", keywords: ["idea", "light"]),
        .init(name: "lock", char: "🔒", keywords: ["secure", "private"]),
        .init(name: "unlock", char: "🔓", keywords: ["open"]),
        .init(name: "key", char: "🔑", keywords: ["password", "unlock"]),
        .init(name: "hammer", char: "🔨", keywords: ["tool", "build"]),
        .init(name: "wrench", char: "🔧", keywords: ["tool", "fix"]),
        .init(name: "gear", char: "⚙️", keywords: ["settings", "config"]),
        .init(name: "hourglass", char: "⌛", keywords: ["time", "wait"]),
        .init(name: "alarm_clock", char: "⏰", keywords: ["time", "wake"]),
        .init(name: "watch", char: "⌚", keywords: ["time"]),
        .init(name: "telephone", char: "☎️", keywords: ["call", "phone"]),
        .init(name: "iphone", char: "📱", keywords: ["phone", "mobile"]),
        .init(name: "computer", char: "💻", keywords: ["laptop", "code", "pc"]),
        .init(name: "desktop_computer", char: "🖥️", keywords: ["pc"]),
        .init(name: "keyboard", char: "⌨️", keywords: ["type"]),
        .init(name: "printer", char: "🖨️", keywords: ["print"]),
        .init(name: "floppy_disk", char: "💾", keywords: ["save"]),
        .init(name: "cd", char: "💿", keywords: ["disc"]),
        .init(name: "battery", char: "🔋", keywords: ["power"]),
        .init(name: "mag", char: "🔍", keywords: ["search", "find", "zoom"]),
        .init(name: "link", char: "🔗", keywords: ["url", "chain"]),
        .init(name: "paperclip", char: "📎", keywords: ["attach"]),
        .init(name: "pushpin", char: "📌", keywords: ["pin"]),
        .init(name: "calendar", char: "📅", keywords: ["date", "schedule"]),
        .init(name: "memo", char: "📝", keywords: ["note", "write", "edit"]),
        .init(name: "book", char: "📖", keywords: ["read"]),
        .init(name: "books", char: "📚", keywords: ["read", "library"]),
        .init(name: "envelope", char: "✉️", keywords: ["mail", "email"]),
        .init(name: "email", char: "📧", keywords: ["mail"]),
        .init(name: "package", char: "📦", keywords: ["box", "ship"]),
        .init(name: "bell", char: "🔔", keywords: ["notification", "alert"]),
        .init(name: "no_bell", char: "🔕", keywords: ["mute"]),
        .init(name: "loudspeaker", char: "📢", keywords: ["announce"]),
        .init(name: "mega", char: "📣", keywords: ["announce", "shout"]),
        .init(name: "musical_note", char: "🎵", keywords: ["music", "song"]),
        .init(name: "notes", char: "🎶", keywords: ["music"]),
        .init(name: "microphone", char: "🎤", keywords: ["sing", "mic"]),
        .init(name: "headphones", char: "🎧", keywords: ["music", "audio"]),
        .init(name: "guitar", char: "🎸", keywords: ["music", "rock"]),
        .init(name: "game_die", char: "🎲", keywords: ["dice", "random"]),
        .init(name: "dart", char: "🎯", keywords: ["target", "bullseye"]),
        .init(name: "video_game", char: "🎮", keywords: ["gaming", "controller"]),
        .init(name: "soccer", char: "⚽", keywords: ["football", "sport"]),
        .init(name: "basketball", char: "🏀", keywords: ["sport"]),
        .init(name: "football", char: "🏈", keywords: ["sport"]),
        .init(name: "baseball", char: "⚾", keywords: ["sport"]),
        .init(name: "tennis", char: "🎾", keywords: ["sport"]),
        // Animals & nature
        .init(name: "dog", char: "🐶", keywords: ["puppy", "pet"]),
        .init(name: "cat", char: "🐱", keywords: ["kitten", "pet"]),
        .init(name: "mouse", char: "🐭", keywords: ["rodent"]),
        .init(name: "hamster", char: "🐹", keywords: ["pet"]),
        .init(name: "rabbit", char: "🐰", keywords: ["bunny"]),
        .init(name: "fox_face", char: "🦊", keywords: ["fox"]),
        .init(name: "bear", char: "🐻", keywords: ["animal"]),
        .init(name: "panda_face", char: "🐼", keywords: ["panda"]),
        .init(name: "koala", char: "🐨", keywords: ["animal"]),
        .init(name: "tiger", char: "🐯", keywords: ["animal"]),
        .init(name: "lion", char: "🦁", keywords: ["animal"]),
        .init(name: "cow", char: "🐮", keywords: ["animal"]),
        .init(name: "pig", char: "🐷", keywords: ["animal"]),
        .init(name: "frog", char: "🐸", keywords: ["animal"]),
        .init(name: "monkey_face", char: "🐵", keywords: ["animal"]),
        .init(name: "chicken", char: "🐔", keywords: ["animal", "hen"]),
        .init(name: "penguin", char: "🐧", keywords: ["animal"]),
        .init(name: "bird", char: "🐦", keywords: ["animal"]),
        .init(name: "baby_chick", char: "🐤", keywords: ["chicken"]),
        .init(name: "eagle", char: "🦅", keywords: ["bird"]),
        .init(name: "owl", char: "🦉", keywords: ["bird"]),
        .init(name: "bat", char: "🦇", keywords: ["animal"]),
        .init(name: "wolf", char: "🐺", keywords: ["animal"]),
        .init(name: "horse", char: "🐴", keywords: ["animal"]),
        .init(name: "unicorn", char: "🦄", keywords: ["magic"]),
        .init(name: "bee", char: "🐝", keywords: ["honey", "insect"]),
        .init(name: "bug", char: "🐛", keywords: ["insect"]),
        .init(name: "butterfly", char: "🦋", keywords: ["insect"]),
        .init(name: "snail", char: "🐌", keywords: ["slow"]),
        .init(name: "lady_beetle", char: "🐞", keywords: ["ladybug"]),
        .init(name: "spider", char: "🕷️", keywords: ["insect"]),
        .init(name: "turtle", char: "🐢", keywords: ["slow", "animal"]),
        .init(name: "snake", char: "🐍", keywords: ["animal"]),
        .init(name: "dragon", char: "🐉", keywords: ["fantasy"]),
        .init(name: "whale", char: "🐳", keywords: ["ocean"]),
        .init(name: "dolphin", char: "🐬", keywords: ["ocean"]),
        .init(name: "fish", char: "🐟", keywords: ["ocean"]),
        .init(name: "shark", char: "🦈", keywords: ["ocean"]),
        .init(name: "octopus", char: "🐙", keywords: ["ocean"]),
        .init(name: "crab", char: "🦀", keywords: ["ocean"]),
        .init(name: "snowman", char: "⛄", keywords: ["winter", "snow"]),
        .init(name: "evergreen_tree", char: "🌲", keywords: ["tree", "nature"]),
        .init(name: "deciduous_tree", char: "🌳", keywords: ["tree"]),
        .init(name: "palm_tree", char: "🌴", keywords: ["beach", "tropical"]),
        .init(name: "cactus", char: "🌵", keywords: ["desert"]),
        .init(name: "four_leaf_clover", char: "🍀", keywords: ["luck"]),
        .init(name: "maple_leaf", char: "🍁", keywords: ["autumn", "fall"]),
        .init(name: "mushroom", char: "🍄", keywords: ["fungi"]),
        .init(name: "rose", char: "🌹", keywords: ["flower", "love"]),
        .init(name: "sunflower", char: "🌻", keywords: ["flower"]),
        .init(name: "tulip", char: "🌷", keywords: ["flower"]),
        .init(name: "blossom", char: "🌼", keywords: ["flower"]),
        .init(name: "cherry_blossom", char: "🌸", keywords: ["flower", "sakura"]),
        .init(name: "earth_americas", char: "🌎", keywords: ["world", "globe"]),
        .init(name: "moon", char: "🌙", keywords: ["night"]),
        .init(name: "full_moon", char: "🌕", keywords: ["night"]),
        .init(name: "comet", char: "☄️", keywords: ["space"]),
        // Food & drink
        .init(name: "apple", char: "🍎", keywords: ["fruit"]),
        .init(name: "green_apple", char: "🍏", keywords: ["fruit"]),
        .init(name: "orange", char: "🍊", keywords: ["fruit"]),
        .init(name: "lemon", char: "🍋", keywords: ["fruit", "sour"]),
        .init(name: "banana", char: "🍌", keywords: ["fruit"]),
        .init(name: "watermelon", char: "🍉", keywords: ["fruit"]),
        .init(name: "grapes", char: "🍇", keywords: ["fruit"]),
        .init(name: "strawberry", char: "🍓", keywords: ["fruit"]),
        .init(name: "cherries", char: "🍒", keywords: ["fruit"]),
        .init(name: "peach", char: "🍑", keywords: ["fruit", "butt"]),
        .init(name: "pineapple", char: "🍍", keywords: ["fruit"]),
        .init(name: "avocado", char: "🥑", keywords: ["fruit"]),
        .init(name: "eggplant", char: "🍆", keywords: ["vegetable"]),
        .init(name: "tomato", char: "🍅", keywords: ["vegetable"]),
        .init(name: "corn", char: "🌽", keywords: ["vegetable"]),
        .init(name: "hot_pepper", char: "🌶️", keywords: ["spicy"]),
        .init(name: "broccoli", char: "🥦", keywords: ["vegetable", "healthy"]),
        .init(name: "bread", char: "🍞", keywords: ["food"]),
        .init(name: "croissant", char: "🥐", keywords: ["food", "french"]),
        .init(name: "cheese", char: "🧀", keywords: ["food"]),
        .init(name: "egg", char: "🥚", keywords: ["food"]),
        .init(name: "bacon", char: "🥓", keywords: ["food", "breakfast"]),
        .init(name: "hamburger", char: "🍔", keywords: ["food", "burger"]),
        .init(name: "fries", char: "🍟", keywords: ["food"]),
        .init(name: "pizza", char: "🍕", keywords: ["food"]),
        .init(name: "hotdog", char: "🌭", keywords: ["food"]),
        .init(name: "taco", char: "🌮", keywords: ["food", "mexican"]),
        .init(name: "burrito", char: "🌯", keywords: ["food", "mexican"]),
        .init(name: "ramen", char: "🍜", keywords: ["food", "noodles"]),
        .init(name: "spaghetti", char: "🍝", keywords: ["food", "pasta"]),
        .init(name: "sushi", char: "🍣", keywords: ["food", "japanese"]),
        .init(name: "rice", char: "🍚", keywords: ["food"]),
        .init(name: "curry", char: "🍛", keywords: ["food"]),
        .init(name: "fried_shrimp", char: "🍤", keywords: ["food"]),
        .init(name: "popcorn", char: "🍿", keywords: ["movie", "snack"]),
        .init(name: "doughnut", char: "🍩", keywords: ["food", "donut"]),
        .init(name: "cookie", char: "🍪", keywords: ["food", "snack"]),
        .init(name: "chocolate_bar", char: "🍫", keywords: ["food", "candy"]),
        .init(name: "candy", char: "🍬", keywords: ["sweet"]),
        .init(name: "lollipop", char: "🍭", keywords: ["sweet"]),
        .init(name: "ice_cream", char: "🍦", keywords: ["dessert"]),
        .init(name: "cake", char: "🍰", keywords: ["dessert"]),
        .init(name: "pie", char: "🥧", keywords: ["dessert"]),
        .init(name: "coffee", char: "☕", keywords: ["drink", "tea", "caffeine"]),
        .init(name: "tea", char: "🍵", keywords: ["drink"]),
        .init(name: "beer", char: "🍺", keywords: ["drink", "alcohol"]),
        .init(name: "beers", char: "🍻", keywords: ["drink", "cheers"]),
        .init(name: "wine_glass", char: "🍷", keywords: ["drink", "alcohol"]),
        .init(name: "cocktail", char: "🍸", keywords: ["drink", "alcohol"]),
        .init(name: "tropical_drink", char: "🍹", keywords: ["drink", "vacation"]),
        .init(name: "champagne", char: "🍾", keywords: ["drink", "celebrate"]),
        .init(name: "clinking_glasses", char: "🥂", keywords: ["cheers", "toast"]),
        .init(name: "tumbler_glass", char: "🥃", keywords: ["whiskey"]),
        // Travel & places
        .init(name: "car", char: "🚗", keywords: ["vehicle", "drive"]),
        .init(name: "taxi", char: "🚕", keywords: ["vehicle"]),
        .init(name: "bus", char: "🚌", keywords: ["vehicle"]),
        .init(name: "ambulance", char: "🚑", keywords: ["emergency"]),
        .init(name: "fire_engine", char: "🚒", keywords: ["emergency"]),
        .init(name: "police_car", char: "🚓", keywords: ["cops"]),
        .init(name: "truck", char: "🚚", keywords: ["delivery"]),
        .init(name: "tractor", char: "🚜", keywords: ["farm"]),
        .init(name: "bike", char: "🚲", keywords: ["bicycle"]),
        .init(name: "motorcycle", char: "🏍️", keywords: ["vehicle"]),
        .init(name: "airplane", char: "✈️", keywords: ["flight", "travel"]),
        .init(name: "helicopter", char: "🚁", keywords: ["fly"]),
        .init(name: "rocket_ship", char: "🚀", keywords: ["space"]),
        .init(name: "ship", char: "🚢", keywords: ["boat"]),
        .init(name: "sailboat", char: "⛵", keywords: ["boat"]),
        .init(name: "speedboat", char: "🚤", keywords: ["boat"]),
        .init(name: "train", char: "🚆", keywords: ["rail"]),
        .init(name: "bullettrain_side", char: "🚄", keywords: ["fast"]),
        .init(name: "house", char: "🏠", keywords: ["home"]),
        .init(name: "office", char: "🏢", keywords: ["building", "work"]),
        .init(name: "hospital", char: "🏥", keywords: ["medical"]),
        .init(name: "school", char: "🏫", keywords: ["education"]),
        .init(name: "hotel", char: "🏨", keywords: ["stay"]),
        .init(name: "bank", char: "🏦", keywords: ["money"]),
        .init(name: "church", char: "⛪", keywords: ["religion"]),
        .init(name: "statue_of_liberty", char: "🗽", keywords: ["nyc", "usa"]),
        .init(name: "bridge_at_night", char: "🌉", keywords: ["city"]),
        .init(name: "city_sunset", char: "🌆", keywords: ["dusk"]),
        .init(name: "tent", char: "⛺", keywords: ["camp"]),
        .init(name: "mountain", char: "⛰️", keywords: ["nature"]),
        .init(name: "volcano", char: "🌋", keywords: ["eruption"]),
        .init(name: "beach_umbrella", char: "🏖️", keywords: ["vacation"]),
        .init(name: "desert_island", char: "🏝️", keywords: ["tropical"]),
        // Misc / flags-ish
        .init(name: "flag_white", char: "🏳️", keywords: ["surrender"]),
        .init(name: "flag_black", char: "🏴", keywords: ["pirate"]),
        .init(name: "triangular_flag_on_post", char: "🚩", keywords: ["red flag"]),
        .init(name: "rainbow_flag", char: "🏳️‍🌈", keywords: ["pride", "lgbt"]),
        .init(name: "100_points", char: "💯", keywords: ["perfect"]),
        .init(name: "ok", char: "🆗", keywords: ["okay"]),
        .init(name: "new", char: "🆕", keywords: ["fresh"]),
        .init(name: "up", char: "🆙", keywords: ["upgrade"]),
        .init(name: "cool", char: "🆒", keywords: ["awesome"]),
        .init(name: "free", char: "🆓", keywords: ["gratis"]),
        .init(name: "sos", char: "🆘", keywords: ["help", "emergency"]),
        .init(name: "arrow_right", char: "➡️", keywords: ["next"]),
        .init(name: "arrow_left", char: "⬅️", keywords: ["back"]),
        .init(name: "arrow_up", char: "⬆️", keywords: ["top"]),
        .init(name: "arrow_down", char: "⬇️", keywords: ["bottom"]),
        .init(name: "arrows_counterclockwise", char: "🔄", keywords: ["refresh", "sync"]),
        .init(name: "repeat", char: "🔁", keywords: ["loop"]),
        .init(name: "back", char: "🔙", keywords: ["return"]),
        .init(name: "soon", char: "🔜", keywords: ["coming"]),
        .init(name: "play", char: "▶️", keywords: ["start"]),
        .init(name: "pause_button", char: "⏸️", keywords: ["stop"]),
        .init(name: "stop_button", char: "⏹️", keywords: ["halt"]),
        .init(name: "fast_forward", char: "⏩", keywords: ["skip"]),
        .init(name: "rewind", char: "⏪", keywords: ["back"]),
        .init(name: "heavy_dollar_sign", char: "💲", keywords: ["money"]),
        .init(name: "tm", char: "™️", keywords: ["trademark"]),
        .init(name: "copyright", char: "©️", keywords: ["legal"]),
        .init(name: "registered", char: "®️", keywords: ["legal"]),
    ]
}
